# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yunzai_nonebot/rpc/hola.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dyunzai_nonebot/rpc/hola.proto\x12\x04hola\"\x1a\n\nOptionCode\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x04\"+\n\x07Request\x12\x0f\n\x07self_id\x18\x01 \x01(\t\x12\x0f\n\x07request\x18\x02 \x01(\x04\"\x1c\n\x08Response\x12\x10\n\x08response\x18\x01 \x01(\x04\x32\x66\n\x04Pipe\x12.\n\x06Option\x12\x10.hola.OptionCode\x1a\x10.hola.OptionCode\"\x00\x12.\n\x07\x43hannel\x12\r.hola.Request\x1a\x0e.hola.Response\"\x00(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yunzai_nonebot.rpc.hola_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OPTIONCODE._serialized_start=39
  _OPTIONCODE._serialized_end=65
  _REQUEST._serialized_start=67
  _REQUEST._serialized_end=110
  _RESPONSE._serialized_start=112
  _RESPONSE._serialized_end=140
  _PIPE._serialized_start=142
  _PIPE._serialized_end=244
# @@protoc_insertion_point(module_scope)
